CREATE TABLE `${tablePrefix}progress_operations` (
    `operation_id` BINARY(16) NOT NULL,
    `fingerprint_version` SMALLINT UNSIGNED NOT NULL,
    `request_fingerprint` BINARY(32) NOT NULL,
    `type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `player_uuid` BINARY(16) NOT NULL,
    `related_player_uuid` BINARY(16) NULL,
    `requested_amount` BIGINT NOT NULL,
    `actor_type` VARCHAR(16) NOT NULL,
    `actor_uuid` BINARY(16) NULL,
    `source_plugin` VARCHAR(64) NOT NULL,
    `reason_key` VARCHAR(128) NOT NULL,
    `server_id` VARCHAR(64) NOT NULL,
    `metadata_json` JSON NOT NULL,
    `result_version` SMALLINT UNSIGNED NULL,
    `result_json` JSON NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `completed_at` DATETIME(6) NULL,
    PRIMARY KEY (`operation_id`),
    INDEX `idx_progress_operations_player_created` (`player_uuid`, `created_at`, `operation_id`),
    INDEX `idx_progress_operations_related_player` (`related_player_uuid`),
    CHECK (`operation_id` <> UNHEX('00000000000000000000000000000000')),
    CHECK (`fingerprint_version` > 0),
    CHECK (`type` IN ('AWARD', 'CREDIT', 'DEBIT', 'TRANSFER', 'SET_BALANCE', 'RESET_BALANCE')),
    CHECK (`status` IN ('PENDING', 'SUCCESS', 'NO_POINTS_AWARDED', 'INSUFFICIENT_FUNDS', 'BALANCE_LIMIT_EXCEEDED')),
    CHECK (`player_uuid` <> UNHEX('00000000000000000000000000000000')),
    CHECK (`related_player_uuid` IS NULL OR `related_player_uuid` <> UNHEX('00000000000000000000000000000000')),
    CHECK (`related_player_uuid` IS NULL OR `related_player_uuid` <> `player_uuid`),
    CHECK (`requested_amount` >= 0),
    CHECK (`actor_type` IN ('SYSTEM', 'PLUGIN', 'PLAYER', 'CONSOLE')),
    CHECK ((`actor_type` = 'PLAYER' AND `actor_uuid` IS NOT NULL) OR (`actor_type` <> 'PLAYER' AND `actor_uuid` IS NULL)),
    CHECK (`actor_uuid` IS NULL OR `actor_uuid` <> UNHEX('00000000000000000000000000000000')),
    CHECK ((`status` = 'PENDING' AND `completed_at` IS NULL) OR (`status` <> 'PENDING' AND `completed_at` IS NOT NULL)),
    CHECK (`completed_at` IS NULL OR `completed_at` >= `created_at`),
    CHECK ((`result_version` IS NULL AND `result_json` IS NULL) OR (`result_version` IS NOT NULL AND `result_json` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
